[project]
name = "3rd-assignment-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.7.2",
    "google-generativeai>=0.8.5",
    "openai-agents>=0.2.10",
    "python-decouple>=3.8",
]
